services:
  web:
    build: .
    container_name: vetly-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FIREBASE_CREDENTIALS_PATH: ${FIREBASE_CREDENTIALS_PATH}
      JAVA_OPTS: ${JAVA_OPTS}
    volumes:
      - ./firebase-service-account.json:/app/config/firebase-service-account.json:ro
    depends_on:
      - database
    networks:
      - spring-network

  database:
    image: postgres
    container_name: vetly-database
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql:ro
      - ../sql/insertTable.sql:/docker-entrypoint-initdb.d/insertTable.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge