services:
  web:
    ports:
      - "8080:8080"
    volumes:
      - ./firebase-service-account.json:/app/config/firebase-service-account.json:ro
    environment:
      SPRING_PROFILES_ACTIVE: dev

  database:
    ports:
      - "5432:5432"
    volumes:
      - ../sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql:ro
      - ../sql/insertTable.sql:/docker-entrypoint-initdb.d/insertTable.sql:ro