services:
  web:
    build: ./server
    container_name: vetly-backend
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      FIREBASE_CREDENTIALS_PATH: ${FIREBASE_CREDENTIALS_PATH}
      PORT: ${PORT}
      JAVA_OPTS: ${JAVA_OPTS}
    volumes:
      - ./server/src/main/resources/serviceAccount.json:/app/config/serviceAccount.json:ro
    depends_on:
      - database
    networks:
      - spring-network

  database:
    image: postgres
    container_name: vetly-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
    - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql:ro
      - ./sql/insertTable.sql:/docker-entrypoint-initdb.d/insertTable.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network: